modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/SrRapero720/FancyMenu-Video/issues"
logoFile="pack.png"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    credits="Special thanks to Kek"
    logoFile="pack.png"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="fancymenu"
    mandatory=true
    ordering="AFTER"
    versionRange="${fancymenu_version_range}"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="watermedia"
    mandatory=true
    versionRange="${watermedia_version_range}"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange = "${loader_version_range}"
    ordering="NONE"
    side="CLIENT"